name: Perf charts
# Run on request and every day at 0300 PT
on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * *

jobs:
  get-circt:
    name: get circt
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/circt/images/circt:nightly
    steps:
      - name: ls
        run: ls
      - name: version
        run: firtool --version
