name: Perf charts
# Run on request and every day at 0300 PT
on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * *

jobs:
  get-circt:
    name: get circt
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/circt/images/circt:nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: NPM?
        run: npm --version
      - run: node --version
      - name: install fuzzer
        run: npm i
      - name: version
        run: firtool --help

