name: Perf charts
# Run on request and every day at 0300 PT
on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * *

jobs:
  firtool-perf:
    name: firtool performance
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/circt/images/circt:nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install fuzzer
        run: npm i
      - name: generate test1.fir
        run: ./node_modules/.bin/circt-fuzzer fir -m 20 -I 1000 -O 1000 -L true -z true -n -o test1.fir
      - name: firtool
        run: firtool test1.fir --lower-to-rtl --enable-lower-types --pass-timing --verilog -o=test1_new.v &> docs/`date +"%Y-%m-%d-%H-%M"`.log
      - name: publish log
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: trunk
          folder: docs
