name: Web App

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build web app
      run: |
        npm i
        npm run build
    - name: publish pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        folder: docs
        clean: false
